package az.turn.api;

public enum SecureUploadFailure {
    EMPTY_FILE,
    FILE_TOO_LARGE,
    UNSUPPORTED_FILE_TYPE,
    INVALID_IMAGE,
    IMAGE_DIMENSIONS_EXCEEDED,
    MALWARE_DETECTED,
    SCANNER_UNAVAILABLE,
    STORAGE_UNAVAILABLE,
    OWNER_NOT_FOUND
}
