package az.turn.api;

public enum SessionState {
    ACTIVE,
    SESSION_NOT_FOUND,
    SESSION_REVOKED,
    SESSION_IDLE_TIMEOUT,
    SESSION_ABSOLUTE_TIMEOUT,
    ACCOUNT_DISABLED,
    CREDENTIALS_CHANGED,
    REFRESH_TOKEN_REUSE,
    ACCESS_TOKEN_EXPIRED,
    ACCESS_TOKEN_INVALID
}
