apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - namespace.yaml
  - stage-secret-metadata.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-internal-service.yaml
  - api-management-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-api
    newTag: c2fa1d680b87b2fd875a1b7903e462d0aa687728
