apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - namespace.yaml
  - stage-secret-metadata.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-internal-service.yaml
  - api-management-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-api
    newTag: 144357a0c1e255d773097e768c3d0bbe95b27ee1
