apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turn-stage

resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - uploads-pvc.yaml
  - clamav-pvc.yaml
  - clamav-deployment.yaml
  - clamav-service.yaml
  - clamav-network-policy.yaml
  - epoint-sandbox-deployment.yaml
  - epoint-sandbox-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-internal-service.yaml
  - api-management-service.yaml
  - ingress.yaml

configMapGenerator:
  - name: epoint-sandbox-checkout-assets
    files:
      - tokens.css=epoint-sandbox-assets/tokens.css
      - checkout.css=epoint-sandbox-assets/checkout.css
      - logo.svg=epoint-sandbox-assets/logo.svg
      - base.html=epoint-sandbox-assets/base.html

images:
  - name: ghcr.io/ilhamzefer-sketch/turn-api
    newTag: b7aa0aa5bd502c474ea931733f3eaceecd2ff5bf
