create table if not exists users (
    id bigint generated by default as identity primary key,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    normalized_phone varchar(13) not null unique,
    password_hash varchar(255),
    status varchar(50) not null,
    invited_first_name varchar(80),
    invited_last_name varchar(80),
    created_by_user_id bigint,
    failed_login_attempts integer not null default 0,
    locked_until timestamp,
    activated_at timestamp,
    last_login_at timestamp,
    password_changed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_users_created_by_user
        foreign key (created_by_user_id)
        references users (id),
    constraint chk_users_status
        check (status in ('PENDING', 'ACTIVE', 'PASSWORD_RESET_REQUIRED', 'SUSPENDED', 'ANONYMIZED')),
    constraint chk_users_password_state
        check (
            (status in ('PENDING', 'PASSWORD_RESET_REQUIRED', 'ANONYMIZED') and password_hash is null)
            or (status in ('ACTIVE', 'SUSPENDED') and password_hash is not null)
        )
);

create index if not exists idx_users_created_by_user_id
    on users (created_by_user_id);

alter table refresh_tokens
    add column if not exists last_used_at timestamp;

alter table refresh_tokens
    add column if not exists user_agent varchar(500);

alter table refresh_tokens
    add column if not exists ip_address varchar(64);

create index if not exists idx_refresh_tokens_user_sessions
    on refresh_tokens (user_type, user_id, revoked, expires_at);

alter table guest_queue_entries
    add column if not exists normalized_phone varchar(13);

alter table guest_queue_entries
    add column if not exists linked_user_id bigint;

alter table guest_queue_entries
    drop constraint if exists fk_guest_queue_entries_linked_user;

alter table guest_queue_entries
    add constraint fk_guest_queue_entries_linked_user
        foreign key (linked_user_id)
        references users (id);

create index if not exists idx_guest_queue_entries_normalized_phone
    on guest_queue_entries (normalized_phone);

create index if not exists idx_guest_queue_entries_linked_user
    on guest_queue_entries (linked_user_id, joined_at);

alter table customer_queue_entries
    add column if not exists user_id bigint;

alter table customer_queue_entries
    alter column customer_id drop not null;

alter table customer_queue_entries
    drop constraint if exists fk_customer_queue_entries_user;

alter table customer_queue_entries
    add constraint fk_customer_queue_entries_user
        foreign key (user_id)
        references users (id);

alter table customer_queue_entries
    drop constraint if exists chk_customer_queue_entries_identity;

alter table customer_queue_entries
    add constraint chk_customer_queue_entries_identity
        check (
            (customer_id is not null and user_id is null)
            or (customer_id is null and user_id is not null)
        );

create index if not exists idx_customer_queue_entries_user
    on customer_queue_entries (user_id, joined_at);
