create table if not exists individual_workspaces (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null unique,
    name varchar(160) not null,
    timezone varchar(60) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    archived_at timestamp,
    constraint fk_individual_workspaces_owner foreign key (owner_user_id) references users (id),
    constraint chk_individual_workspaces_status check (status in ('ACTIVE', 'ARCHIVED'))
);

create table if not exists businesses (
    id bigint generated by default as identity primary key,
    primary_owner_user_id bigint not null,
    name varchar(160) not null,
    legal_name varchar(200),
    description varchar(2000),
    tax_id varchar(40),
    logo_url varchar(1000),
    normalized_phone varchar(13) not null,
    timezone varchar(60) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    archived_at timestamp,
    constraint fk_businesses_primary_owner foreign key (primary_owner_user_id) references users (id),
    constraint chk_businesses_status check (status in ('ACTIVE', 'ARCHIVED'))
);

create index if not exists idx_businesses_primary_owner on businesses (primary_owner_user_id);

create table if not exists business_memberships (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    user_id bigint not null,
    role varchar(30) not null,
    status varchar(30) not null,
    invited_by_user_id bigint not null,
    invited_first_name varchar(80),
    invited_last_name varchar(80),
    created_pending_user boolean not null default false,
    invited_at timestamp not null default current_timestamp,
    accepted_at timestamp,
    rejected_at timestamp,
    removed_at timestamp,
    constraint uk_business_memberships_business_user unique (business_id, user_id),
    constraint fk_business_memberships_business foreign key (business_id) references businesses (id),
    constraint fk_business_memberships_user foreign key (user_id) references users (id),
    constraint fk_business_memberships_inviter foreign key (invited_by_user_id) references users (id),
    constraint chk_business_memberships_role check (role in ('PRIMARY_OWNER', 'ADMIN', 'EMPLOYEE')),
    constraint chk_business_memberships_status check (status in ('PENDING_ACCEPTANCE', 'ACTIVE', 'REJECTED', 'SUSPENDED', 'REMOVED'))
);

create index if not exists idx_business_memberships_user_status on business_memberships (user_id, status);
create index if not exists idx_business_memberships_business_status on business_memberships (business_id, status);
create index if not exists idx_business_memberships_invite_limits on business_memberships (business_id, invited_by_user_id, invited_at, created_pending_user);

create table if not exists branches (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    name varchar(160) not null,
    address varchar(500) not null,
    city varchar(120) not null,
    district varchar(120) not null,
    latitude decimal(9,6),
    longitude decimal(9,6),
    normalized_phone varchar(13),
    notes varchar(2000),
    timezone varchar(60) not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    archived_at timestamp,
    constraint fk_branches_business foreign key (business_id) references businesses (id),
    constraint chk_branches_status check (status in ('ACTIVE', 'ARCHIVED')),
    constraint chk_branches_latitude check (latitude is null or latitude between -90 and 90),
    constraint chk_branches_longitude check (longitude is null or longitude between -180 and 180)
);

create index if not exists idx_branches_business_status on branches (business_id, status);

create table if not exists rooms (
    id bigint generated by default as identity primary key,
    branch_id bigint,
    individual_workspace_id bigint unique,
    created_by_user_id bigint not null,
    name varchar(160) not null,
    room_number_or_code varchar(80),
    description varchar(2000),
    notes varchar(2000),
    timezone varchar(60) not null,
    reservation_mode varchar(30) not null,
    default_slot_duration_minutes integer not null,
    status varchar(30) not null,
    visibility varchar(30) not null,
    personal_public_address varchar(500),
    personal_latitude decimal(9,6),
    personal_longitude decimal(9,6),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    archived_at timestamp,
    constraint fk_rooms_branch foreign key (branch_id) references branches (id),
    constraint fk_rooms_individual_workspace foreign key (individual_workspace_id) references individual_workspaces (id),
    constraint fk_rooms_creator foreign key (created_by_user_id) references users (id),
    constraint chk_rooms_owner_scope check (
        (branch_id is not null and individual_workspace_id is null)
        or (branch_id is null and individual_workspace_id is not null)
    ),
    constraint chk_rooms_mode check (reservation_mode in ('LIVE_QUEUE', 'PLANNED_BOOKING')),
    constraint chk_rooms_duration check (default_slot_duration_minutes between 1 and 1440),
    constraint chk_rooms_status check (status in ('DRAFT', 'PUBLISHED', 'INACTIVE', 'ARCHIVED')),
    constraint chk_rooms_visibility check (visibility in ('PUBLIC', 'UNLISTED', 'PRIVATE')),
    constraint chk_rooms_personal_latitude check (personal_latitude is null or personal_latitude between -90 and 90),
    constraint chk_rooms_personal_longitude check (personal_longitude is null or personal_longitude between -180 and 180)
);

create index if not exists idx_rooms_branch_status on rooms (branch_id, status);
create index if not exists idx_rooms_creator on rooms (created_by_user_id);

create table if not exists room_assignments (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    user_id bigint not null,
    role varchar(30) not null,
    status varchar(30) not null,
    invited_by_user_id bigint not null,
    show_phone_publicly boolean not null default false,
    invited_at timestamp not null default current_timestamp,
    responded_at timestamp,
    revoked_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint uk_room_assignments_room_user unique (room_id, user_id),
    constraint fk_room_assignments_room foreign key (room_id) references rooms (id),
    constraint fk_room_assignments_user foreign key (user_id) references users (id),
    constraint fk_room_assignments_inviter foreign key (invited_by_user_id) references users (id),
    constraint chk_room_assignments_role check (role = 'ROOM_OWNER'),
    constraint chk_room_assignments_status check (status in ('PENDING_ACCEPTANCE', 'ACTIVE', 'REJECTED', 'REVOKED'))
);

create index if not exists idx_room_assignments_user_status on room_assignments (user_id, status);
create index if not exists idx_room_assignments_room_status on room_assignments (room_id, status);
