alter table rooms
    add column if not exists appointment_buffer_minutes integer not null default 0;

alter table rooms
    add column if not exists booking_window_days integer not null default 30;

alter table rooms
    add column if not exists minimum_advance_minutes integer not null default 30;

alter table rooms
    add column if not exists cancellation_cutoff_minutes integer not null default 0;

alter table rooms
    add column if not exists live_queue_reset_policy varchar(30);

alter table rooms
    add column if not exists live_queue_reset_local_time time;

alter table rooms
    add column if not exists live_queue_reset_interval_minutes integer;

alter table rooms
    add column if not exists live_queue_max_participants integer;

alter table rooms
    add column if not exists live_queue_accepting_new_entries boolean not null default true;

alter table rooms
    add constraint chk_rooms_appointment_buffer
        check (appointment_buffer_minutes between 0 and 1440);

alter table rooms
    add constraint chk_rooms_booking_window
        check (booking_window_days between 1 and 90);

alter table rooms
    add constraint chk_rooms_minimum_advance
        check (minimum_advance_minutes between 0 and 10080);

alter table rooms
    add constraint chk_rooms_cancellation_cutoff
        check (cancellation_cutoff_minutes >= 0);

alter table rooms
    add constraint chk_rooms_live_queue_limit
        check (live_queue_max_participants is null or live_queue_max_participants > 0);

alter table rooms
    add constraint chk_rooms_live_queue_reset
        check (
            (live_queue_reset_policy is null
                and live_queue_reset_local_time is null
                and live_queue_reset_interval_minutes is null)
            or (live_queue_reset_policy = 'DAILY_AT_TIME'
                and live_queue_reset_local_time is not null
                and live_queue_reset_interval_minutes is null)
            or (live_queue_reset_policy = 'EVERY_INTERVAL'
                and live_queue_reset_local_time is null
                and live_queue_reset_interval_minutes > 0)
        );

create table if not exists room_services (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    name varchar(160) not null,
    description varchar(1000),
    price decimal(12,2),
    currency varchar(3),
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_room_services_room foreign key (room_id) references rooms (id),
    constraint chk_room_services_price check (price is null or price >= 0),
    constraint chk_room_services_currency check (
        (price is null and currency is null)
        or (price is not null and currency = 'AZN')
    )
);

create index if not exists idx_room_services_room_active on room_services (room_id, active);

create table if not exists weekly_availability_rules (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    day_of_week varchar(10) not null,
    start_time time not null,
    end_time time not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_weekly_availability_room foreign key (room_id) references rooms (id),
    constraint uk_weekly_availability_interval unique (room_id, day_of_week, start_time, end_time),
    constraint chk_weekly_availability_day check (
        day_of_week in ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    ),
    constraint chk_weekly_availability_interval check (start_time < end_time)
);

create index if not exists idx_weekly_availability_room_day
    on weekly_availability_rules (room_id, day_of_week, start_time);

create table if not exists availability_exceptions (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    exception_date date not null,
    type varchar(30) not null,
    start_time time,
    end_time time,
    reason varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_availability_exceptions_room foreign key (room_id) references rooms (id),
    constraint chk_availability_exceptions_type check (
        type in ('CLOSED', 'CUSTOM_HOURS', 'BLOCKED_INTERVAL')
    ),
    constraint chk_availability_exceptions_interval check (
        (type = 'CLOSED' and start_time is null and end_time is null)
        or (type in ('CUSTOM_HOURS', 'BLOCKED_INTERVAL')
            and start_time is not null
            and end_time is not null
            and start_time < end_time)
    )
);

create index if not exists idx_availability_exceptions_room_date
    on availability_exceptions (room_id, exception_date, start_time);
