create table if not exists guest_contacts (
    id bigint generated by default as identity primary key,
    display_name varchar(160) not null,
    normalized_phone varchar(13) not null unique,
    linked_user_id bigint,
    created_at timestamp not null default current_timestamp,
    linked_at timestamp,
    constraint fk_guest_contacts_user foreign key (linked_user_id) references users (id)
);

create index if not exists idx_guest_contacts_linked_user on guest_contacts (linked_user_id);

create table if not exists live_queue_sessions (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    service_date date not null,
    status varchar(30) not null,
    open_slot integer,
    acceptance_override varchar(30) not null,
    reset_policy varchar(30) not null,
    reset_local_time time,
    reset_interval_minutes integer,
    next_reset_at timestamp not null,
    next_position bigint not null default 0,
    opened_at timestamp not null,
    closed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_live_queue_sessions_room foreign key (room_id) references rooms (id),
    constraint uk_live_queue_sessions_open unique (room_id, open_slot),
    constraint chk_live_queue_sessions_status check (status in ('OPEN', 'CLOSED', 'CANCELLED')),
    constraint chk_live_queue_sessions_open_slot check (
        (status = 'OPEN' and open_slot = 1)
        or (status <> 'OPEN' and open_slot is null)
    ),
    constraint chk_live_queue_sessions_acceptance check (
        acceptance_override in ('AUTO', 'FORCE_OPEN', 'FORCE_CLOSED')
    ),
    constraint chk_live_queue_sessions_reset_policy check (
        reset_policy in ('DAILY_AT_TIME', 'EVERY_INTERVAL')
    ),
    constraint chk_live_queue_sessions_reset check (
        (reset_policy = 'DAILY_AT_TIME' and reset_local_time is not null and reset_interval_minutes is null)
        or (reset_policy = 'EVERY_INTERVAL' and reset_local_time is null and reset_interval_minutes > 0)
    )
);

create index if not exists idx_live_queue_sessions_room_created
    on live_queue_sessions (room_id, created_at desc);
create index if not exists idx_live_queue_sessions_due_reset
    on live_queue_sessions (status, next_reset_at);

create table if not exists live_queue_entries (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    room_id bigint not null,
    user_id bigint,
    guest_contact_id bigint,
    queue_position bigint not null,
    public_reference varchar(24) not null unique,
    status varchar(30) not null,
    source varchar(30) not null,
    active_identity_key varchar(20),
    current_slot integer,
    private_display_name varchar(160),
    internal_note varchar(1000),
    created_by_user_id bigint,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    completed_at timestamp,
    removed_at timestamp,
    constraint fk_live_queue_entries_session foreign key (session_id) references live_queue_sessions (id),
    constraint fk_live_queue_entries_room foreign key (room_id) references rooms (id),
    constraint fk_live_queue_entries_user foreign key (user_id) references users (id),
    constraint fk_live_queue_entries_guest foreign key (guest_contact_id) references guest_contacts (id),
    constraint fk_live_queue_entries_creator foreign key (created_by_user_id) references users (id),
    constraint uk_live_queue_entries_position unique (session_id, queue_position),
    constraint uk_live_queue_entries_active_identity unique (session_id, active_identity_key),
    constraint uk_live_queue_entries_current unique (session_id, current_slot),
    constraint chk_live_queue_entries_identity check (
        (user_id is not null and guest_contact_id is null)
        or (user_id is null and guest_contact_id is not null)
    ),
    constraint chk_live_queue_entries_status check (
        status in ('WAITING', 'CURRENT', 'SKIPPED', 'COMPLETED', 'REMOVED', 'RESET')
    ),
    constraint chk_live_queue_entries_source check (
        source in ('WEB', 'QR', 'OWNER_PHONE', 'OWNER_WALK_IN', 'OWNER_OTHER')
    ),
    constraint chk_live_queue_entries_current_slot check (
        (status = 'CURRENT' and current_slot = 1)
        or (status <> 'CURRENT' and current_slot is null)
    ),
    constraint chk_live_queue_entries_active_identity check (
        (status in ('WAITING', 'CURRENT', 'SKIPPED') and active_identity_key is not null)
        or (status not in ('WAITING', 'CURRENT', 'SKIPPED') and active_identity_key is null)
    )
);

create index if not exists idx_live_queue_entries_session_status_position
    on live_queue_entries (session_id, status, queue_position);
create index if not exists idx_live_queue_entries_user_created
    on live_queue_entries (user_id, created_at desc);
create index if not exists idx_live_queue_entries_guest_created
    on live_queue_entries (guest_contact_id, created_at desc);

create table if not exists qr_credentials (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    token_hash varchar(64) not null unique,
    type varchar(30) not null,
    active boolean not null default true,
    created_by_user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    revoked_at timestamp,
    constraint fk_qr_credentials_room foreign key (room_id) references rooms (id),
    constraint fk_qr_credentials_creator foreign key (created_by_user_id) references users (id),
    constraint chk_qr_credentials_type check (type = 'PERMANENT_ROOM')
);

create index if not exists idx_qr_credentials_room_active on qr_credentials (room_id, active);
