create table if not exists planned_bookings (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    user_id bigint,
    guest_contact_id bigint,
    room_service_id bigint,
    booking_reference varchar(24) not null unique,
    status varchar(30) not null,
    source varchar(30) not null,
    start_at timestamp not null,
    end_at timestamp not null,
    blocking_end_at timestamp not null,
    active_slot integer,
    active_customer_slot integer,
    customer_note varchar(1000),
    internal_note varchar(1000),
    cancellation_reason varchar(30),
    cancellation_detail varchar(500),
    created_by_user_id bigint,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    completed_at timestamp,
    cancelled_at timestamp,
    constraint fk_planned_bookings_room foreign key (room_id) references rooms (id),
    constraint fk_planned_bookings_user foreign key (user_id) references users (id),
    constraint fk_planned_bookings_guest foreign key (guest_contact_id) references guest_contacts (id),
    constraint fk_planned_bookings_service foreign key (room_service_id) references room_services (id),
    constraint fk_planned_bookings_creator foreign key (created_by_user_id) references users (id),
    constraint uk_planned_bookings_active_start unique (room_id, start_at, active_slot),
    constraint uk_planned_bookings_active_customer unique (room_id, user_id, active_customer_slot),
    constraint chk_planned_bookings_identity check (
        (user_id is not null and guest_contact_id is null)
        or (user_id is null and guest_contact_id is not null)
    ),
    constraint chk_planned_bookings_status check (status in ('ACTIVE', 'COMPLETED', 'CANCELLED')),
    constraint chk_planned_bookings_source check (
        source in ('WEB', 'OWNER_PHONE', 'OWNER_WALK_IN', 'OWNER_OTHER')
    ),
    constraint chk_planned_bookings_interval check (
        start_at < end_at and end_at <= blocking_end_at
    ),
    constraint chk_planned_bookings_active_slots check (
        (status = 'ACTIVE' and active_slot = 1
            and ((user_id is not null and active_customer_slot = 1)
                or (user_id is null and active_customer_slot is null)))
        or (status <> 'ACTIVE' and active_slot is null and active_customer_slot is null)
    ),
    constraint chk_planned_bookings_cancellation check (
        (status = 'CANCELLED' and cancellation_reason is not null and cancelled_at is not null)
        or (status <> 'CANCELLED' and cancellation_reason is null and cancelled_at is null)
    )
);

create index if not exists idx_planned_bookings_room_start
    on planned_bookings (room_id, start_at);
create index if not exists idx_planned_bookings_user_start
    on planned_bookings (user_id, start_at desc);
create index if not exists idx_planned_bookings_guest_start
    on planned_bookings (guest_contact_id, start_at desc);

create table if not exists booking_audit_events (
    id bigint generated by default as identity primary key,
    booking_id bigint not null,
    action varchar(30) not null,
    actor_user_id bigint not null,
    old_start_at timestamp,
    old_end_at timestamp,
    new_start_at timestamp,
    new_end_at timestamp,
    reason varchar(500),
    participant_informed boolean not null default false,
    created_at timestamp not null default current_timestamp,
    constraint fk_booking_audit_booking foreign key (booking_id) references planned_bookings (id),
    constraint fk_booking_audit_actor foreign key (actor_user_id) references users (id),
    constraint chk_booking_audit_action check (
        action in ('CREATED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED')
    )
);

create index if not exists idx_booking_audit_booking_created
    on booking_audit_events (booking_id, created_at);
