create table if not exists subscription_plans (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name varchar(120) not null,
    billing_period varchar(20) not null,
    amount bigint not null,
    currency varchar(3) not null,
    room_limit integer not null,
    employee_limit integer not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    constraint chk_subscription_plans_period check (billing_period in ('MONTHLY', 'YEARLY')),
    constraint chk_subscription_plans_amount check (amount > 0),
    constraint chk_subscription_plans_limits check (room_limit > 0 and employee_limit > 0)
);

insert into subscription_plans (code, name, billing_period, amount, currency, room_limit, employee_limit)
select 'STANDARD_MONTHLY', 'Standard Monthly', 'MONTHLY', 20, 'AZN', 100, 500
where not exists (select 1 from subscription_plans where code = 'STANDARD_MONTHLY');

insert into subscription_plans (code, name, billing_period, amount, currency, room_limit, employee_limit)
select 'STANDARD_YEARLY', 'Standard Yearly', 'YEARLY', 200, 'AZN', 100, 500
where not exists (select 1 from subscription_plans where code = 'STANDARD_YEARLY');

create table if not exists provider_subscriptions (
    id bigint generated by default as identity primary key,
    scope_type varchar(30) not null,
    scope_id bigint not null,
    plan_id bigint not null,
    billing_period varchar(20) not null,
    status varchar(30) not null,
    room_limit integer not null,
    employee_limit integer not null,
    starts_at timestamp,
    expires_at timestamp,
    grace_ends_at timestamp,
    usage_grace_ends_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_provider_subscriptions_scope unique (scope_type, scope_id),
    constraint fk_provider_subscriptions_plan foreign key (plan_id) references subscription_plans (id),
    constraint chk_provider_subscriptions_scope check (scope_type in ('INDIVIDUAL_WORKSPACE', 'BUSINESS')),
    constraint chk_provider_subscriptions_period check (billing_period in ('MONTHLY', 'YEARLY')),
    constraint chk_provider_subscriptions_status check (
        status in ('PENDING_PAYMENT', 'ACTIVE', 'GRACE_PERIOD', 'SUSPENDED', 'CANCELLED')
    )
);

create index if not exists idx_provider_subscriptions_status_expiry
    on provider_subscriptions (status, expires_at, grace_ends_at);

alter table payment_sessions add column if not exists provider_subscription_id bigint;
alter table payment_sessions add column if not exists subscription_plan_id bigint;
alter table payment_sessions add column if not exists payment_purpose varchar(30) default 'LEGACY_REGISTRATION';
update payment_sessions set payment_purpose = 'LEGACY_REGISTRATION' where payment_purpose is null;
alter table payment_sessions alter column payment_purpose set not null;
alter table payment_sessions alter column registration_type drop not null;
alter table payment_sessions alter column first_name drop not null;
alter table payment_sessions alter column last_name drop not null;
alter table payment_sessions alter column email drop not null;
alter table payment_sessions alter column password_hash drop not null;

alter table payment_sessions drop constraint if exists fk_payment_sessions_provider_subscription;
alter table payment_sessions add constraint fk_payment_sessions_provider_subscription
    foreign key (provider_subscription_id) references provider_subscriptions (id);
alter table payment_sessions drop constraint if exists fk_payment_sessions_subscription_plan;
alter table payment_sessions add constraint fk_payment_sessions_subscription_plan
    foreign key (subscription_plan_id) references subscription_plans (id);
alter table payment_sessions drop constraint if exists chk_payment_sessions_purpose;
alter table payment_sessions add constraint chk_payment_sessions_purpose
    check (payment_purpose in ('LEGACY_REGISTRATION', 'PROVIDER_SUBSCRIPTION'));

create index if not exists idx_payment_sessions_subscription
    on payment_sessions (provider_subscription_id, created_at);

create table if not exists account_ownership_disputes (
    id bigint generated by default as identity primary key,
    disputed_user_id bigint,
    disputed_phone varchar(13) not null,
    claimant_name varchar(160) not null,
    claimant_contact_phone varchar(13) not null,
    description varchar(2000) not null,
    status varchar(30) not null,
    resolution_note varchar(2000),
    resolution_action varchar(30),
    reviewed_by_admin varchar(120),
    password_reset_required_at timestamp,
    created_at timestamp not null default current_timestamp,
    resolved_at timestamp,
    constraint fk_account_disputes_user foreign key (disputed_user_id) references users (id),
    constraint chk_account_disputes_status check (status in ('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED')),
    constraint chk_account_disputes_action check (
        resolution_action is null or resolution_action in ('NO_ACTION', 'SUSPEND', 'RESET_PASSWORD', 'RESTORE_ACCESS')
    )
);

create table if not exists phone_change_requests (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    current_normalized_phone varchar(13) not null,
    requested_normalized_phone varchar(13) not null,
    reason varchar(1000) not null,
    status varchar(30) not null,
    reviewed_by_admin varchar(120),
    resolution_note varchar(2000),
    created_at timestamp not null default current_timestamp,
    resolved_at timestamp,
    constraint fk_phone_change_requests_user foreign key (user_id) references users (id),
    constraint chk_phone_change_requests_status check (status in ('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED'))
);

create index if not exists idx_phone_change_requests_user_status
    on phone_change_requests (user_id, status);

create table if not exists account_deletion_requests (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    status varchar(30) not null,
    requested_at timestamp not null default current_timestamp,
    processed_by_admin varchar(120),
    processed_at timestamp,
    resolution_note varchar(2000),
    constraint fk_account_deletion_requests_user foreign key (user_id) references users (id),
    constraint chk_account_deletion_requests_status check (status in ('OPEN', 'IN_REVIEW', 'COMPLETED', 'REJECTED'))
);

create index if not exists idx_account_deletion_requests_user_status
    on account_deletion_requests (user_id, status);

create table if not exists business_ownership_transfers (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    from_owner_user_id bigint not null,
    to_admin_user_id bigint not null,
    status varchar(30) not null,
    created_at timestamp not null default current_timestamp,
    responded_at timestamp,
    constraint fk_ownership_transfers_business foreign key (business_id) references businesses (id),
    constraint fk_ownership_transfers_from_user foreign key (from_owner_user_id) references users (id),
    constraint fk_ownership_transfers_to_user foreign key (to_admin_user_id) references users (id),
    constraint chk_ownership_transfers_status check (
        status in ('PENDING_ACCEPTANCE', 'ACCEPTED', 'REJECTED', 'CANCELLED')
    )
);

create index if not exists idx_ownership_transfers_target_status
    on business_ownership_transfers (to_admin_user_id, status);

create table if not exists room_customer_blocks (
    id bigint generated by default as identity primary key,
    room_id bigint not null,
    customer_user_id bigint not null,
    reason varchar(1000) not null,
    blocked_by_user_id bigint not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    revoked_at timestamp,
    revoked_by_user_id bigint,
    constraint uk_room_customer_blocks unique (room_id, customer_user_id),
    constraint fk_room_blocks_room foreign key (room_id) references rooms (id),
    constraint fk_room_blocks_customer foreign key (customer_user_id) references users (id),
    constraint fk_room_blocks_blocker foreign key (blocked_by_user_id) references users (id),
    constraint fk_room_blocks_revoker foreign key (revoked_by_user_id) references users (id)
);

create table if not exists service_ratings (
    id bigint generated by default as identity primary key,
    live_queue_entry_id bigint unique,
    planned_booking_id bigint unique,
    customer_user_id bigint not null,
    room_id bigint not null,
    score integer not null,
    comment varchar(1000),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    editable_until timestamp not null,
    constraint fk_service_ratings_live_entry foreign key (live_queue_entry_id) references live_queue_entries (id),
    constraint fk_service_ratings_booking foreign key (planned_booking_id) references planned_bookings (id),
    constraint fk_service_ratings_customer foreign key (customer_user_id) references users (id),
    constraint fk_service_ratings_room foreign key (room_id) references rooms (id),
    constraint chk_service_ratings_target check (
        (live_queue_entry_id is not null and planned_booking_id is null)
        or (live_queue_entry_id is null and planned_booking_id is not null)
    ),
    constraint chk_service_ratings_score check (score between 1 and 5)
);

create index if not exists idx_service_ratings_room on service_ratings (room_id, created_at);

create table if not exists platform_audit_events (
    id bigint generated by default as identity primary key,
    actor_type varchar(30) not null,
    actor_reference varchar(120) not null,
    action varchar(100) not null,
    target_type varchar(60) not null,
    target_id bigint,
    details varchar(3000),
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_platform_audit_events_target
    on platform_audit_events (target_type, target_id, created_at);

alter table users alter column normalized_phone drop not null;
alter table guest_contacts alter column normalized_phone drop not null;
