create table if not exists business_categories (
    id bigint generated by default as identity primary key,
    code varchar(60) not null unique,
    name_az varchar(120) not null,
    display_order integer not null,
    active boolean not null default true
);

insert into business_categories (code, name_az, display_order)
select 'BEAUTY_PERSONAL_CARE', 'Gözəllik və şəxsi qulluq', 10
where not exists (select 1 from business_categories where code = 'BEAUTY_PERSONAL_CARE');

insert into business_categories (code, name_az, display_order)
select 'HEALTH_MEDICAL', 'Sağlamlıq və tibb', 20
where not exists (select 1 from business_categories where code = 'HEALTH_MEDICAL');

insert into business_categories (code, name_az, display_order)
select 'PROFESSIONAL_SERVICES', 'Peşəkar xidmətlər', 30
where not exists (select 1 from business_categories where code = 'PROFESSIONAL_SERVICES');

insert into business_categories (code, name_az, display_order)
select 'EDUCATION', 'Təhsil', 40
where not exists (select 1 from business_categories where code = 'EDUCATION');

insert into business_categories (code, name_az, display_order)
select 'REPAIR_MAINTENANCE', 'Təmir və texniki xidmət', 50
where not exists (select 1 from business_categories where code = 'REPAIR_MAINTENANCE');

insert into business_categories (code, name_az, display_order)
select 'PUBLIC_SERVICES', 'Dövlət və ictimai xidmətlər', 60
where not exists (select 1 from business_categories where code = 'PUBLIC_SERVICES');

insert into business_categories (code, name_az, display_order)
select 'OTHER', 'Digər', 999
where not exists (select 1 from business_categories where code = 'OTHER');

alter table businesses
    add column if not exists category_id bigint;

alter table businesses
    add column if not exists custom_subcategory varchar(160);

alter table businesses
    add constraint fk_businesses_category
        foreign key (category_id) references business_categories (id);

create index if not exists idx_businesses_category on businesses (category_id);
create index if not exists idx_rooms_public_discovery on rooms (status, visibility, reservation_mode, name);
