create table if not exists registrations (
    id bigint generated by default as identity primary key,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    paid boolean not null,
    payment_reference varchar(255) not null,
    registration_type varchar(255) not null check (registration_type in ('FERDI', 'KORPORATIV'))
);

create table if not exists queues (
    id bigint generated by default as identity primary key,
    registration_id bigint not null,
    address varchar(255) not null,
    service_name varchar(255) not null,
    qr_token varchar(255) not null unique,
    current_queue_number bigint not null,
    constraint fk_queues_registration
        foreign key (registration_id)
        references registrations (id)
);

create table if not exists queue_categories (
    queue_id bigint not null,
    category varchar(255) not null,
    constraint fk_queue_categories_queue
        foreign key (queue_id)
        references queues (id)
);
