create table if not exists refresh_token_history (
    id bigint generated by default as identity primary key,
    refresh_token_id bigint not null,
    token_hash varchar(500) not null unique,
    rotated_at timestamp not null default current_timestamp,
    constraint fk_refresh_token_history_session
        foreign key (refresh_token_id)
        references refresh_tokens (id)
        on delete cascade
);

create index if not exists idx_refresh_token_history_session
    on refresh_token_history (refresh_token_id, rotated_at);
