create table if not exists wallet_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    balance bigint not null default 0,
    version bigint not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_wallet_accounts_user foreign key (user_id) references users (id),
    constraint chk_wallet_accounts_balance check (balance >= 0)
);

insert into wallet_accounts (user_id, balance, version, created_at, updated_at)
select users.id, 0, 0, current_timestamp, current_timestamp
from users
where not exists (
    select 1 from wallet_accounts where wallet_accounts.user_id = users.id
);

create table if not exists wallet_transactions (
    id bigint generated by default as identity primary key,
    wallet_account_id bigint not null,
    transaction_type varchar(40) not null,
    direction varchar(10) not null,
    amount bigint not null,
    balance_before bigint not null,
    balance_after bigint not null,
    actor_type varchar(20) not null,
    actor_user_id bigint,
    actor_reference varchar(160),
    reference_key varchar(180) not null,
    description varchar(1000),
    created_at timestamp not null,
    constraint fk_wallet_transactions_account foreign key (wallet_account_id) references wallet_accounts (id),
    constraint fk_wallet_transactions_actor_user foreign key (actor_user_id) references users (id),
    constraint uk_wallet_transactions_reference unique (wallet_account_id, reference_key),
    constraint chk_wallet_transactions_type check (
        transaction_type in ('ADMIN_CREDIT', 'TOP_UP', 'SUBSCRIPTION_PAYMENT', 'REFUND')
    ),
    constraint chk_wallet_transactions_direction check (direction in ('CREDIT', 'DEBIT')),
    constraint chk_wallet_transactions_type_direction check (
        (transaction_type in ('ADMIN_CREDIT', 'TOP_UP', 'REFUND') and direction = 'CREDIT')
        or (transaction_type = 'SUBSCRIPTION_PAYMENT' and direction = 'DEBIT')
    ),
    constraint chk_wallet_transactions_amount check (amount > 0),
    constraint chk_wallet_transactions_balances check (
        balance_before >= 0
        and balance_after >= 0
        and (
            (direction = 'CREDIT' and balance_after = balance_before + amount)
            or (direction = 'DEBIT' and balance_after = balance_before - amount)
        )
    ),
    constraint chk_wallet_transactions_actor check (
        (actor_type = 'USER' and actor_user_id is not null)
        or (actor_type in ('ADMIN', 'SYSTEM') and actor_reference is not null)
    ),
    constraint chk_wallet_transactions_admin_reason check (
        transaction_type <> 'ADMIN_CREDIT'
        or (description is not null and trim(description) <> '')
    ),
    constraint chk_wallet_transactions_admin_actor check (
        transaction_type <> 'ADMIN_CREDIT' or actor_type = 'ADMIN'
    )
);

create index if not exists idx_wallet_transactions_history
    on wallet_transactions (wallet_account_id, created_at, id);

create index if not exists idx_wallet_transactions_actor_user
    on wallet_transactions (actor_user_id, created_at);
