alter table subscription_plans add column if not exists scope_type varchar(30);
alter table subscription_plans add column if not exists coin_price bigint;

update subscription_plans set active = false where code in ('STANDARD_MONTHLY', 'STANDARD_YEARLY');

insert into subscription_plans (
    code, name, billing_period, amount, currency, room_limit, employee_limit, active, scope_type, coin_price
)
select 'INDIVIDUAL_MONTHLY', 'Fərdi aylıq', 'MONTHLY', 3, 'AZN', 1, 1, true, 'INDIVIDUAL_WORKSPACE', 30
where not exists (select 1 from subscription_plans where code = 'INDIVIDUAL_MONTHLY');

insert into subscription_plans (
    code, name, billing_period, amount, currency, room_limit, employee_limit, active, scope_type, coin_price
)
select 'BUSINESS_MONTHLY', 'Biznes aylıq', 'MONTHLY', 10, 'AZN', 5, 500, true, 'BUSINESS', 100
where not exists (select 1 from subscription_plans where code = 'BUSINESS_MONTHLY');

update provider_subscriptions
set plan_id = (select id from subscription_plans where code = 'INDIVIDUAL_MONTHLY'),
    billing_period = 'MONTHLY',
    room_limit = 1,
    employee_limit = 1,
    updated_at = current_timestamp
where scope_type = 'INDIVIDUAL_WORKSPACE';

update provider_subscriptions
set plan_id = (select id from subscription_plans where code = 'BUSINESS_MONTHLY'),
    billing_period = 'MONTHLY',
    room_limit = greatest(
        5,
        cast((
            select count(*)
            from rooms
            join branches on branches.id = rooms.branch_id
            where branches.business_id = provider_subscriptions.scope_id
              and rooms.status <> 'ARCHIVED'
        ) as integer)
    ),
    employee_limit = 500,
    updated_at = current_timestamp
where scope_type = 'BUSINESS';

alter table subscription_plans drop constraint if exists chk_subscription_plans_scope;
alter table subscription_plans add constraint chk_subscription_plans_scope check (
    scope_type is null or scope_type in ('INDIVIDUAL_WORKSPACE', 'BUSINESS')
);
alter table subscription_plans drop constraint if exists chk_subscription_plans_coin_price;
alter table subscription_plans add constraint chk_subscription_plans_coin_price check (
    coin_price is null or coin_price > 0
);

create table if not exists subscription_coin_payments (
    id bigint generated by default as identity primary key,
    payer_user_id bigint not null,
    provider_subscription_id bigint not null,
    subscription_plan_id bigint not null,
    wallet_transaction_id bigint not null unique,
    idempotency_key varchar(80) not null,
    amount bigint not null,
    status varchar(30) not null,
    payment_reference varchar(180) not null unique,
    created_at timestamp not null,
    completed_at timestamp not null,
    constraint fk_subscription_coin_payments_user foreign key (payer_user_id) references users (id),
    constraint fk_subscription_coin_payments_subscription foreign key (provider_subscription_id)
        references provider_subscriptions (id),
    constraint fk_subscription_coin_payments_plan foreign key (subscription_plan_id) references subscription_plans (id),
    constraint fk_subscription_coin_payments_wallet_transaction foreign key (wallet_transaction_id)
        references wallet_transactions (id),
    constraint uk_subscription_coin_payments_idempotency unique (payer_user_id, idempotency_key),
    constraint chk_subscription_coin_payments_amount check (amount > 0),
    constraint chk_subscription_coin_payments_status check (status = 'COMPLETED')
);

create index if not exists idx_subscription_coin_payments_subscription
    on subscription_coin_payments (provider_subscription_id, created_at, id);
