create table if not exists admin_accounts (
    id bigint generated by default as identity primary key,
    username varchar(50) not null unique,
    display_name varchar(120) not null,
    password_hash varchar(255) not null,
    active boolean not null default true,
    created_by_username varchar(50),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint chk_admin_accounts_username check (trim(username) <> ''),
    constraint chk_admin_accounts_display_name check (trim(display_name) <> ''),
    constraint chk_admin_accounts_password_hash check (trim(password_hash) <> '')
);

create index if not exists idx_admin_accounts_active_username
    on admin_accounts (active, username);
