create table if not exists wallet_top_up_packages (
    code varchar(30) primary key,
    amount_azn integer not null unique,
    coin_amount bigint not null unique,
    payment_url varchar(500) not null unique,
    display_order integer not null unique,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    constraint chk_wallet_top_up_packages_amount check (amount_azn in (3, 5, 10, 15, 20)),
    constraint chk_wallet_top_up_packages_coin_amount check (coin_amount = cast(amount_azn as bigint) * 10),
    constraint chk_wallet_top_up_packages_fixed_catalog check (
        (code = 'AZN_3' and amount_azn = 3 and coin_amount = 30
            and payment_url = 'https://cb.birbank.business/pay/7847238243e34c9c9dd4666f749d5879'
            and display_order = 1)
        or (code = 'AZN_5' and amount_azn = 5 and coin_amount = 50
            and payment_url = 'https://cb.birbank.business/pay/89a5510f409341ecbf82badf75512d21'
            and display_order = 2)
        or (code = 'AZN_10' and amount_azn = 10 and coin_amount = 100
            and payment_url = 'https://cb.birbank.business/pay/75c998cbda8e4674bb11cbf961d91c27'
            and display_order = 3)
        or (code = 'AZN_15' and amount_azn = 15 and coin_amount = 150
            and payment_url = 'https://cb.birbank.business/pay/1b0fcb5e4e5f4b23a4ed8ec1b8fbc978'
            and display_order = 4)
        or (code = 'AZN_20' and amount_azn = 20 and coin_amount = 200
            and payment_url = 'https://cb.birbank.business/pay/d2000eed920c4af68dc83106e6b56b9f'
            and display_order = 5)
    )
);

insert into wallet_top_up_packages (
    code, amount_azn, coin_amount, payment_url, display_order, active, created_at
)
select 'AZN_3', 3, 30,
       'https://cb.birbank.business/pay/7847238243e34c9c9dd4666f749d5879',
       1, true, current_timestamp
where not exists (select 1 from wallet_top_up_packages where code = 'AZN_3');

insert into wallet_top_up_packages (
    code, amount_azn, coin_amount, payment_url, display_order, active, created_at
)
select 'AZN_5', 5, 50,
       'https://cb.birbank.business/pay/89a5510f409341ecbf82badf75512d21',
       2, true, current_timestamp
where not exists (select 1 from wallet_top_up_packages where code = 'AZN_5');

insert into wallet_top_up_packages (
    code, amount_azn, coin_amount, payment_url, display_order, active, created_at
)
select 'AZN_10', 10, 100,
       'https://cb.birbank.business/pay/75c998cbda8e4674bb11cbf961d91c27',
       3, true, current_timestamp
where not exists (select 1 from wallet_top_up_packages where code = 'AZN_10');

insert into wallet_top_up_packages (
    code, amount_azn, coin_amount, payment_url, display_order, active, created_at
)
select 'AZN_15', 15, 150,
       'https://cb.birbank.business/pay/1b0fcb5e4e5f4b23a4ed8ec1b8fbc978',
       4, true, current_timestamp
where not exists (select 1 from wallet_top_up_packages where code = 'AZN_15');

insert into wallet_top_up_packages (
    code, amount_azn, coin_amount, payment_url, display_order, active, created_at
)
select 'AZN_20', 20, 200,
       'https://cb.birbank.business/pay/d2000eed920c4af68dc83106e6b56b9f',
       5, true, current_timestamp
where not exists (select 1 from wallet_top_up_packages where code = 'AZN_20');

create table if not exists wallet_top_up_requests (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    active_user_id bigint unique,
    package_code varchar(30) not null,
    amount_azn integer not null,
    coin_amount bigint not null,
    currency varchar(3) not null,
    payment_url varchar(500) not null,
    status varchar(30) not null,
    clicked_at timestamp not null,
    receipt_deadline_at timestamp not null,
    receipt_uploaded_at timestamp,
    reviewed_by_admin_id bigint,
    reviewed_at timestamp,
    resolution_note varchar(1000),
    wallet_transaction_id bigint unique,
    version bigint not null default 0,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_wallet_top_up_requests_user foreign key (user_id) references users (id),
    constraint fk_wallet_top_up_requests_active_user foreign key (active_user_id) references users (id),
    constraint fk_wallet_top_up_requests_package foreign key (package_code) references wallet_top_up_packages (code),
    constraint fk_wallet_top_up_requests_admin foreign key (reviewed_by_admin_id) references admin_accounts (id),
    constraint fk_wallet_top_up_requests_transaction foreign key (wallet_transaction_id)
        references wallet_transactions (id),
    constraint chk_wallet_top_up_requests_status check (
        status in ('AWAITING_RECEIPT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED')
    ),
    constraint chk_wallet_top_up_requests_currency check (currency = 'AZN'),
    constraint chk_wallet_top_up_requests_time_window check (
        receipt_deadline_at = clicked_at + interval '30' minute
        and receipt_deadline_at > clicked_at
        and (receipt_uploaded_at is null or receipt_uploaded_at < receipt_deadline_at)
        and (reviewed_at is null or (receipt_uploaded_at is not null and reviewed_at >= receipt_uploaded_at))
        and updated_at >= created_at
    ),
    constraint chk_wallet_top_up_requests_fixed_package check (
        (package_code = 'AZN_3' and amount_azn = 3 and coin_amount = 30
            and payment_url = 'https://cb.birbank.business/pay/7847238243e34c9c9dd4666f749d5879')
        or (package_code = 'AZN_5' and amount_azn = 5 and coin_amount = 50
            and payment_url = 'https://cb.birbank.business/pay/89a5510f409341ecbf82badf75512d21')
        or (package_code = 'AZN_10' and amount_azn = 10 and coin_amount = 100
            and payment_url = 'https://cb.birbank.business/pay/75c998cbda8e4674bb11cbf961d91c27')
        or (package_code = 'AZN_15' and amount_azn = 15 and coin_amount = 150
            and payment_url = 'https://cb.birbank.business/pay/1b0fcb5e4e5f4b23a4ed8ec1b8fbc978')
        or (package_code = 'AZN_20' and amount_azn = 20 and coin_amount = 200
            and payment_url = 'https://cb.birbank.business/pay/d2000eed920c4af68dc83106e6b56b9f')
    ),
    constraint chk_wallet_top_up_requests_state check (
        (status = 'AWAITING_RECEIPT'
            and active_user_id = user_id
            and receipt_uploaded_at is null
            and reviewed_by_admin_id is null
            and reviewed_at is null
            and resolution_note is null
            and wallet_transaction_id is null)
        or (status = 'PENDING_REVIEW'
            and active_user_id = user_id
            and receipt_uploaded_at is not null
            and reviewed_by_admin_id is null
            and reviewed_at is null
            and resolution_note is null
            and wallet_transaction_id is null)
        or (status = 'APPROVED'
            and active_user_id is null
            and receipt_uploaded_at is not null
            and reviewed_by_admin_id is not null
            and reviewed_at is not null
            and resolution_note is null
            and wallet_transaction_id is not null)
        or (status = 'REJECTED'
            and active_user_id is null
            and receipt_uploaded_at is not null
            and reviewed_by_admin_id is not null
            and reviewed_at is not null
            and resolution_note is not null
            and trim(resolution_note) <> ''
            and wallet_transaction_id is null)
        or (status = 'EXPIRED'
            and active_user_id is null
            and receipt_uploaded_at is null
            and reviewed_by_admin_id is null
            and reviewed_at is null
            and resolution_note is null
            and wallet_transaction_id is null)
    )
);

create index if not exists idx_wallet_top_up_requests_user_history
    on wallet_top_up_requests (user_id, created_at, id);

create index if not exists idx_wallet_top_up_requests_admin_queue
    on wallet_top_up_requests (status, receipt_uploaded_at, id);
