create table if not exists secure_attachments (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    purpose varchar(40) not null,
    storage_key varchar(80) not null unique,
    original_filename varchar(180) not null,
    media_type varchar(30) not null,
    file_extension varchar(10) not null,
    size_bytes bigint not null,
    width_pixels integer not null,
    height_pixels integer not null,
    sha256 varchar(64) not null,
    scan_status varchar(20) not null,
    scanned_at timestamp not null,
    created_at timestamp not null,
    constraint fk_secure_attachments_owner foreign key (owner_user_id) references users (id),
    constraint chk_secure_attachments_purpose check (
        purpose in ('PAYMENT_RECEIPT', 'SUPPORT_REQUEST')
    ),
    constraint chk_secure_attachments_media check (
        (media_type = 'image/jpeg' and file_extension = 'jpg')
        or (media_type = 'image/png' and file_extension = 'png')
    ),
    constraint chk_secure_attachments_size check (size_bytes between 1 and 5242880),
    constraint chk_secure_attachments_dimensions check (
        width_pixels between 1 and 10000
        and height_pixels between 1 and 10000
        and cast(width_pixels as bigint) * cast(height_pixels as bigint) <= 25000000
    ),
    constraint chk_secure_attachments_sha256 check (
        length(sha256) = 64 and lower(sha256) = sha256
    ),
    constraint chk_secure_attachments_scan check (
        scan_status = 'CLEAN' and scanned_at <= created_at
    ),
    constraint chk_secure_attachments_filename check (
        trim(original_filename) <> ''
        and position('/' in original_filename) = 0
        and position('\\' in original_filename) = 0
    )
);

create index if not exists idx_secure_attachments_owner_created
    on secure_attachments (owner_user_id, created_at, id);

create index if not exists idx_secure_attachments_purpose_created
    on secure_attachments (purpose, created_at, id);
