create table if not exists user_support_requests (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    request_type varchar(20) not null,
    message varchar(4000) not null,
    status varchar(30) not null default 'OPEN',
    support_attachment_id bigint unique,
    reviewed_by_admin_id bigint,
    admin_response varchar(4000),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    reviewed_at timestamp,
    version bigint not null default 0,
    constraint fk_user_support_requests_user foreign key (user_id) references users (id),
    constraint fk_user_support_requests_attachment foreign key (support_attachment_id) references secure_attachments (id),
    constraint fk_user_support_requests_admin foreign key (reviewed_by_admin_id) references admin_accounts (id),
    constraint chk_user_support_requests_type check (request_type in ('PROBLEM', 'SUGGESTION')),
    constraint chk_user_support_requests_status check (status in ('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED')),
    constraint chk_user_support_requests_message check (trim(message) <> ''),
    constraint chk_user_support_requests_dates check (updated_at >= created_at),
    constraint chk_user_support_requests_review check (
        (status = 'OPEN' and reviewed_by_admin_id is null and reviewed_at is null and admin_response is null)
        or (status in ('IN_REVIEW', 'RESOLVED', 'REJECTED') and reviewed_by_admin_id is not null and reviewed_at is not null)
    ),
    constraint chk_user_support_requests_terminal_response check (
        status in ('OPEN', 'IN_REVIEW') or (admin_response is not null and trim(admin_response) <> '')
    )
);

create index if not exists idx_user_support_requests_admin_queue
    on user_support_requests (status, request_type, created_at, id);

create index if not exists idx_user_support_requests_user_history
    on user_support_requests (user_id, created_at, id);
