alter table queues
    add column if not exists current_serving_number bigint default 0;

alter table queues
    add column if not exists last_issued_number bigint default 0;

alter table queues
    add column if not exists average_service_minutes bigint default 5;

alter table queues
    add column if not exists served_customers_count bigint default 0;

alter table queues
    add column if not exists total_service_minutes bigint default 0;

alter table queues
    add column if not exists last_advanced_at timestamp;

update queues
set last_issued_number = current_queue_number
where last_issued_number is null or last_issued_number = 0;

alter table queues
    alter column current_serving_number set not null;

alter table queues
    alter column last_issued_number set not null;

alter table queues
    alter column average_service_minutes set not null;

alter table queues
    alter column served_customers_count set not null;

alter table queues
    alter column total_service_minutes set not null;

create table if not exists queue_managers (
    id bigint generated by default as identity primary key,
    queue_id bigint not null unique,
    username varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_queue_managers_queue
        foreign key (queue_id)
        references queues (id)
);
