create table if not exists customers (
    id bigint generated by default as identity primary key,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists customer_queue_entries (
    id bigint generated by default as identity primary key,
    customer_id bigint not null,
    queue_id bigint not null,
    queue_number bigint not null,
    display_name varchar(255),
    rating integer,
    rating_note varchar(500),
    joined_at timestamp not null default current_timestamp,
    constraint fk_customer_queue_entries_customer
        foreign key (customer_id)
        references customers (id),
    constraint fk_customer_queue_entries_queue
        foreign key (queue_id)
        references queues (id)
);
