alter table queues
    add column if not exists reset_mode varchar(50) not null default 'DAILY';

alter table queues
    add column if not exists reset_at timestamp;

alter table queues
    add column if not exists active boolean not null default true;

create table if not exists guest_queue_entries (
    id bigint generated by default as identity primary key,
    queue_id bigint not null,
    queue_number bigint not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    joined_at timestamp not null default current_timestamp,
    constraint fk_guest_queue_entries_queue
        foreign key (queue_id)
        references queues (id)
);
