create table if not exists refresh_tokens (
    id bigint generated by default as identity primary key,
    token varchar(500) not null unique,
    user_type varchar(50) not null,
    user_id bigint,
    username varchar(255) not null,
    expires_at timestamp not null,
    revoked boolean not null default false,
    created_at timestamp not null default current_timestamp
);
